number=int(input("Enter your number:"))
print("1 to the power of ",number,"is",number**1)
print("2 to the power of ",number,"is",number**2)
print("3 to the power of ",number,"is",number**3)
print("4 to the power of ",number,"is",number**4)
print("5 to the power of ",number,"is",number**5)
print("6 to the power of ",number,"is",number**6)
print("7 to the power of ",number,"is",number**7)
print("8 to the power of",number,"is",number**8)
print("9 to the power of",number,"is",number**9)
print("10 to the power of",number,"is",number**10)
print("11 to the power of",number,"is",number**11)
print("12 to the power of",number,"is",number**12)